-- 002_mockup_seed.sql
-- Initial application data seeded from the static Littop mockup pages.
BEGIN;

-- users and author profiles from the mockup
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('alexander.pushkin@mockup.littop.local', 'alexander-pushkin', 'seeded-password-hash', 'author', 'active', '2026-01-02T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Александр Пушкин', 'Классик русской словесности из витрины макета.', 'Москва', NULL, 980, 0, TRUE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'alexander-pushkin' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('alexander.blok@mockup.littop.local', 'alexander-blok', 'seeded-password-hash', 'author', 'active', '2026-01-03T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Александр Блок', 'Классик русской поэзии из витрины макета.', 'Санкт-Петербург', NULL, 930, 0, TRUE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'alexander-blok' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('sergey.esenin@mockup.littop.local', 'sergey-esenin', 'seeded-password-hash', 'author', 'active', '2026-01-04T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Сергей Есенин', 'Классический поэт из витрины макета.', 'Рязань', NULL, 945, 0, TRUE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'sergey-esenin' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('bulat.okudzhava@mockup.littop.local', 'bulat-okudzhava', 'seeded-password-hash', 'author', 'active', '2026-01-05T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Булат Окуджава', 'Классик авторской песни и поэзии из макета.', 'Москва', NULL, 910, 0, TRUE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'bulat-okudzhava' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('vladimir.vysotsky@mockup.littop.local', 'vladimir-vysotsky', 'seeded-password-hash', 'author', 'active', '2026-01-06T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Владимир Высоцкий', 'Классик авторской песни и поэзии из витрины макета.', 'Москва', NULL, 970, 0, TRUE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'vladimir-vysotsky' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('stan242@mockup.littop.local', 'Stan242', 'seeded-password-hash', 'author', 'active', '2026-01-07T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Олег Сталь', 'Автор из первой страницы списка авторов макета.', 'Москва', NULL, 88, 0, FALSE, TRUE, 'mockup://authors' FROM users u WHERE u.login = 'Stan242' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('dave.gahan@mockup.littop.local', 'Dave_Gahan', 'seeded-password-hash', 'author', 'active', '2026-01-08T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Дейв Гахан', 'Автор из первой страницы списка авторов макета.', 'Санкт-Петербург', NULL, 74, 0, FALSE, TRUE, 'mockup://authors' FROM users u WHERE u.login = 'Dave_Gahan' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('the.king.of.words@mockup.littop.local', 'the_king_of_words', 'seeded-password-hash', 'author', 'active', '2026-01-09T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Sergei Небогатый', 'Автор из первой страницы списка авторов макета.', 'Минск', NULL, 71, 0, FALSE, TRUE, 'mockup://authors' FROM users u WHERE u.login = 'the_king_of_words' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('ergin@mockup.littop.local', 'ergin', 'seeded-password-hash', 'author', 'active', '2026-01-10T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Виктор Ергин', 'Автор из первой страницы списка авторов макета.', 'Казань', NULL, 69, 0, FALSE, TRUE, 'mockup://authors' FROM users u WHERE u.login = 'ergin' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('anton.borovikov@mockup.littop.local', 'antonborovikov', 'seeded-password-hash', 'author', 'active', '2026-01-11T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Антон Боровиков', 'Автор из первой страницы списка авторов макета.', 'Екатеринбург', NULL, 65, 0, FALSE, TRUE, 'mockup://authors' FROM users u WHERE u.login = 'antonborovikov' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('ardak1977@mockup.littop.local', 'Ardak1977', 'seeded-password-hash', 'author', 'active', '2026-01-12T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Ardak Kassymbek', 'Автор из первой страницы списка авторов макета.', 'Алматы', NULL, 63, 0, FALSE, TRUE, 'mockup://authors' FROM users u WHERE u.login = 'Ardak1977' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('alevtina55@mockup.littop.local', 'Alevtina55', 'seeded-password-hash', 'author', 'active', '2026-01-13T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Алевтина Хоментовская', 'Автор из первой страницы списка авторов макета.', 'Самара', NULL, 22, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'Alevtina55' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('mirevgvlad@mail.ru', 'mirevgvlad_mail_ru', 'seeded-password-hash', 'author', 'active', '2026-01-14T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Евгений Мирмович', 'Автор из первой страницы списка авторов макета.', 'Владивосток', NULL, 20, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'mirevgvlad_mail_ru' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('martinova@mockup.littop.local', 'Martinova', 'seeded-password-hash', 'author', 'active', '2026-01-15T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Бабинцева Анна', 'Автор из первой страницы списка авторов макета.', 'Пермь', NULL, 18, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'Martinova' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('talman27@mockup.littop.local', 'Talman27', 'seeded-password-hash', 'author', 'active', '2026-01-16T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Кирилл Матюшкин', 'Автор из первой страницы списка авторов макета.', 'Томск', NULL, 19, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'Talman27' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('dakotov_k@mockup.littop.local', 'Dakotov_k', 'seeded-password-hash', 'author', 'active', '2026-01-17T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Литературные презентации', 'Автор из первой страницы списка авторов макета.', 'Новосибирск', NULL, 17, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'Dakotov_k' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('galina030847@mockup.littop.local', 'galina030847', 'seeded-password-hash', 'author', 'active', '2026-01-18T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Галина Лебединская', 'Автор из первой страницы списка авторов макета.', 'Омск', NULL, 16, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'galina030847' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('golnevv@mockup.littop.local', 'golnevv', 'seeded-password-hash', 'author', 'active', '2026-01-19T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Виталий Гольнев', 'Автор из первой страницы списка авторов макета.', 'Краснодар', NULL, 15, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'golnevv' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('strong47@mockup.littop.local', 'strong47', 'seeded-password-hash', 'author', 'active', '2026-01-20T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Сергей Корчагин', 'Автор из первой страницы списка авторов макета.', 'Нижний Новгород', NULL, 14, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'strong47' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('olga.snopova@mockup.littop.local', 'olga-snopova', 'seeded-password-hash', 'author', 'active', '2026-01-21T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Ольга Снопова', 'Автор из первой страницы списка авторов макета.', 'Тула', NULL, 62, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'olga-snopova' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('petrovna@mockup.littop.local', 'PETROVNA', 'seeded-password-hash', 'author', 'active', '2026-01-22T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Петровна Краса', 'Автор из первой страницы списка авторов макета.', 'Ярославль', NULL, 6, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'PETROVNA' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('sadmelandbanane@mockup.littop.local', 'Sadmelandbanane', 'seeded-password-hash', 'author', 'active', '2026-01-23T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Света Сантурян', 'Автор из первой страницы списка авторов макета.', 'Ростов-на-Дону', NULL, 8, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'Sadmelandbanane' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('ilyamurmuromec@mockup.littop.local', 'Ilyamurmuromec', 'seeded-password-hash', 'author', 'active', '2026-01-24T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Илья Поляков', 'Автор из первой страницы списка авторов макета.', 'Воронеж', NULL, 9, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'Ilyamurmuromec' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('kasaurart@mockup.littop.local', 'KasaurArt', 'seeded-password-hash', 'author', 'active', '2026-01-25T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Kas Aur', 'Автор из первой страницы списка авторов макета.', 'Алматы', NULL, 11, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'KasaurArt' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('grustniy.poet@mockup.littop.local', 'grustniy_poet', 'seeded-password-hash', 'author', 'active', '2026-01-26T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Станислав Попеляев', 'Автор из первой страницы списка авторов макета.', 'Челябинск', NULL, 10, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'grustniy_poet' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('kinosshhii@mockup.littop.local', 'kinosshhii', 'seeded-password-hash', 'author', 'active', '2026-01-27T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Алёна Барбоскина', 'Автор из первой страницы списка авторов макета.', 'Иркутск', NULL, 3, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'kinosshhii' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('alina.veldzh@mockup.littop.local', 'alina-veldzh', 'seeded-password-hash', 'author', 'active', '2026-01-28T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'АЛИНА ВЕЛЬДЖ', 'Автор анонса из раздела произведений макета.', 'Сочи', NULL, 12, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'alina-veldzh' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('loranna@mockup.littop.local', 'Loranna', 'seeded-password-hash', 'author', 'active', '2026-01-29T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Лолита Сойфер', 'Автор анонса из раздела произведений макета.', 'Калининград', NULL, 18, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'Loranna' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('valdorvich@mockup.littop.local', 'valdorvich', 'seeded-password-hash', 'author', 'active', '2026-01-30T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Валерий Доронкин', 'Автор анонса из раздела произведений макета.', 'Белгород', NULL, 21, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'valdorvich' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('dant.ist@mockup.littop.local', 'dant-ist', 'seeded-password-hash', 'author', 'active', '2026-01-31T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'ДанТ исТ', 'Автор анонса из раздела произведений макета.', 'Курск', NULL, 13, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'dant-ist' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('sirena@mockup.littop.local', 'sirena', 'seeded-password-hash', 'author', 'active', '2026-02-01T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'СИрена', 'Автор анонса из раздела произведений макета.', 'Псков', NULL, 19, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'sirena' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('0000109@mockup.littop.local', '0000109', 'seeded-password-hash', 'author', 'active', '2026-02-02T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Юрий Митченко', 'Автор анонса и блока «На крыльце» из макета.', 'Тверь', NULL, 17, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = '0000109' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('marina.novikova.shvedt@mockup.littop.local', 'marina-novikova-shvedt', 'seeded-password-hash', 'author', 'active', '2026-02-03T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Марина Новикова-Шведт', 'Автор анонса из раздела произведений макета.', 'Смоленск', NULL, 23, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'marina-novikova-shvedt' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('sasha.samsonov@mockup.littop.local', 'sasha-samsonov', 'seeded-password-hash', 'author', 'active', '2026-02-04T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'саша самсонов', 'Автор анонса из раздела произведений макета.', 'Киров', NULL, 4, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'sasha-samsonov' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('turbomon@mockup.littop.local', 'turbomon', 'seeded-password-hash', 'author', 'active', '2026-02-05T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Олег Медведев', 'Автор блока «На крыльце» из макета.', 'Пенза', NULL, 15, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'turbomon' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('shchepinska@mockup.littop.local', 'Shchepinska', 'seeded-password-hash', 'author', 'active', '2026-02-06T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Лиза Виолонова', 'Автор блока «На крыльце» из макета.', 'Вильнюс', NULL, 14, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'Shchepinska' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('zvjozddochka@mockup.littop.local', 'ZVJOZDDOCHKA', 'seeded-password-hash', 'author', 'active', '2026-02-07T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'ℨϐëʓ∂⭐∂σ੫ƙα', 'Автор блока «На крыльце» из макета.', 'Рига', NULL, 7, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'ZVJOZDDOCHKA' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('lone.traveler@mockup.littop.local', 'lone_traveler', 'seeded-password-hash', 'author', 'active', '2026-02-08T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Lone Traveler', 'Автор темы из форумного макета.', 'Минск', NULL, 9, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'lone_traveler' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('david.tm@mockup.littop.local', 'david-tm', 'seeded-password-hash', 'author', 'active', '2026-02-09T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Давид', 'Автор темы из форумного макета.', 'Тбилиси', NULL, 8, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'david-tm' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('curator.tm@mockup.littop.local', 'curator-tm', 'seeded-password-hash', 'author', 'active', '2026-02-10T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Куратор ТМ', 'Куратор форумной мастерской из макета.', 'Москва', NULL, 11, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'curator-tm' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('lf@mockup.littop.local', 'lf', 'seeded-password-hash', 'author', 'active', '2026-02-11T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'lf', 'Автор темы из форумного макета.', 'Самара', NULL, 7, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'lf' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('astsergey@mockup.littop.local', 'astsergey', 'seeded-password-hash', 'author', 'active', '2026-02-12T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Астсергей', 'Автор темы из форумного макета.', 'Омск', NULL, 8, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'astsergey' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('elizabet.velyamin@mockup.littop.local', 'elizabet-velyamin-skaya', 'seeded-password-hash', 'author', 'active', '2026-02-13T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Элизабет Вельяминская', 'Автор свежего отзыва из макета.', 'Кострома', NULL, 6, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'elizabet-velyamin-skaya' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;
INSERT INTO users (email, login, password_hash, role, status, registered_at) VALUES ('tais.nikolskaya@mockup.littop.local', 'tais-nikolskaya', 'seeded-password-hash', 'author', 'active', '2026-02-14T09:00:00+03:00') ON CONFLICT DO NOTHING;
INSERT INTO author_profiles (user_id, display_name, bio, city, website_url, rating_total, works_count_cached, is_classic, is_featured, source_url) SELECT u.id, 'Таис Никольская', 'Автор свежего отзыва из макета.', 'Рязань', NULL, 5, 0, FALSE, FALSE, 'mockup://authors' FROM users u WHERE u.login = 'tais-nikolskaya' ON CONFLICT (user_id) DO UPDATE SET display_name = EXCLUDED.display_name, bio = EXCLUDED.bio, city = EXCLUDED.city, website_url = EXCLUDED.website_url, rating_total = EXCLUDED.rating_total, is_classic = EXCLUDED.is_classic, is_featured = EXCLUDED.is_featured, source_url = EXCLUDED.source_url;

-- showcase slots for classics
INSERT INTO author_showcase_slots (slot_type, position, author_user_id, title_override, is_active) SELECT 'classic'::showcase_slot_type, 1, u.id, NULL, TRUE FROM users u WHERE u.login = 'alexander-pushkin' ON CONFLICT (slot_type, position) DO UPDATE SET author_user_id = EXCLUDED.author_user_id, is_active = EXCLUDED.is_active;
INSERT INTO author_showcase_slots (slot_type, position, author_user_id, title_override, is_active) SELECT 'classic'::showcase_slot_type, 2, u.id, NULL, TRUE FROM users u WHERE u.login = 'alexander-blok' ON CONFLICT (slot_type, position) DO UPDATE SET author_user_id = EXCLUDED.author_user_id, is_active = EXCLUDED.is_active;
INSERT INTO author_showcase_slots (slot_type, position, author_user_id, title_override, is_active) SELECT 'classic'::showcase_slot_type, 3, u.id, NULL, TRUE FROM users u WHERE u.login = 'sergey-esenin' ON CONFLICT (slot_type, position) DO UPDATE SET author_user_id = EXCLUDED.author_user_id, is_active = EXCLUDED.is_active;
INSERT INTO author_showcase_slots (slot_type, position, author_user_id, title_override, is_active) SELECT 'classic'::showcase_slot_type, 4, u.id, NULL, TRUE FROM users u WHERE u.login = 'bulat-okudzhava' ON CONFLICT (slot_type, position) DO UPDATE SET author_user_id = EXCLUDED.author_user_id, is_active = EXCLUDED.is_active;
INSERT INTO author_showcase_slots (slot_type, position, author_user_id, title_override, is_active) SELECT 'classic'::showcase_slot_type, 5, u.id, NULL, TRUE FROM users u WHERE u.login = 'vladimir-vysotsky' ON CONFLICT (slot_type, position) DO UPDATE SET author_user_id = EXCLUDED.author_user_id, is_active = EXCLUDED.is_active;

-- works from the mockup pages
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'Сказание о шаманке Нини', 'skazanie-o-shamanke-nini', 'Мистическая поэзия из авторского анонса макета.', 'Сказание о шаманке Нини — мистическая поэзия из авторских анонсов макета. В этой seed-версии сохранён сам заголовок, жанровый контекст и настроение карточки.', 'Мистическая поэзия из авторского анонса макета.', NULL, 'published', '2026-05-15T09:00:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = 'alina-veldzh' AND ws.code = 'poetry' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'skazanie-o-shamanke-nini');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'Поэзия', 'poeziya-loranna', 'Лирика философская из авторского анонса макета.', 'Короткая публикация Лолиты Сойфер из блока авторских анонсов макета.', 'Лирика философская из авторского анонса макета.', NULL, 'published', '2026-05-15T09:10:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = 'Loranna' AND ws.code = 'poetry' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'poeziya-loranna');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'Сольвейг', 'solvejg', 'Стихи, не вошедшие в рубрики — карточка из авторских анонсов.', 'Произведение Валерия Доронкина из блока авторских анонсов макета.', 'Стихи, не вошедшие в рубрики — карточка из авторских анонсов.', NULL, 'published', '2026-05-15T09:20:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = 'valdorvich' AND ws.code = 'poetry' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'solvejg');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'Туше', 'tushe', 'Стихи, не вошедшие в рубрики.', 'Произведение ДанТ исТ из блока авторских анонсов макета.', 'Стихи, не вошедшие в рубрики.', NULL, 'published', '2026-05-15T09:30:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = 'dant-ist' AND ws.code = 'poetry' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'tushe');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'Мы победим', 'my-pobedim', 'Карточка из авторских анонсов макета.', 'Поэтическая публикация ДанТ исТ из блока авторских анонсов макета.', 'Карточка из авторских анонсов макета.', NULL, 'published', '2026-05-15T09:35:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = 'dant-ist' AND ws.code = 'poetry' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'my-pobedim');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'А капелла (Ушедшим родителям)', 'a-kapella', 'Мир души · просмотров: 363 · рецензий: 21.', 'Публикация СИрены из авторских анонсов макета.', 'Мир души · просмотров: 363 · рецензий: 21.', NULL, 'published', '2026-05-15T09:40:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = 'sirena' AND ws.code = 'poetry' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'a-kapella');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'Хор ночных теней', 'hor-nochnyh-tenej', 'Мистическая поэзия из авторского анонса.', 'Публикация Юрия Митченко из блока авторских анонсов макета.', 'Мистическая поэзия из авторского анонса.', NULL, 'published', '2026-05-15T09:45:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = '0000109' AND ws.code = 'poetry' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'hor-nochnyh-tenej');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'Там, где цветёт орешник', 'tam-gde-cvetet-oreshnik', 'Лирика любовная из авторского анонса.', 'Публикация Марины Новиковой-Шведт из блока авторских анонсов макета.', 'Лирика любовная из авторского анонса.', NULL, 'published', '2026-05-15T09:50:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = 'marina-novikova-shvedt' AND ws.code = 'poetry' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'tam-gde-cvetet-oreshnik');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'Плюс, леон', 'plyus-leon', 'Мир души · просмотров: 2.', 'Небольшая публикация саши самсонова из авторских анонсов макета.', 'Мир души · просмотров: 2.', NULL, 'published', '2026-05-15T09:55:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = 'sasha-samsonov' AND ws.code = 'poetry' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'plyus-leon');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'Чёрные монеты', 'chernye-monety', 'Публикация из блока «На крыльце».', 'Текст Олега Медведева из блока «На крыльце» макета.', 'Публикация из блока «На крыльце».', NULL, 'published', '2026-05-15T10:00:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = 'turbomon' AND ws.code = 'poetry' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'chernye-monety');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'Поэт—вселенная, где он пророк!', 'poet-vselennaya', 'Публикация из блока «На крыльце».', 'Текст Валерия Доронкина из блока «На крыльце» макета.', 'Публикация из блока «На крыльце».', NULL, 'published', '2026-05-15T10:05:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = 'valdorvich' AND ws.code = 'poetry' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'poet-vselennaya');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'Давай сегодня помолчим', 'davay-segodnya-pomolchim', 'Публикация из блока «На крыльце».', 'Текст Лолиты Сойфер из блока «На крыльце» макета.', 'Публикация из блока «На крыльце».', NULL, 'published', '2026-05-15T10:10:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = 'Loranna' AND ws.code = 'poetry' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'davay-segodnya-pomolchim');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'записки на песке, монологи стёртых автопортретов', 'zapiski-na-peske', 'Публикация из блока «На крыльце».', 'Прозаическая публикация Лизы Виолоновой из блока «На крыльце» макета.', 'Публикация из блока «На крыльце».', NULL, 'published', '2026-05-15T10:15:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = 'Shchepinska' AND ws.code = 'prose' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'zapiski-na-peske');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'У природы нет плохой погоды, если водка есть и бутерброды.', 'u-prirody-net-plohoy-pogody', 'Публикация из блока «На крыльце».', 'Ироничный текст Юрия Митченко из блока «На крыльце» макета.', 'Публикация из блока «На крыльце».', NULL, 'published', '2026-05-15T10:20:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = '0000109' AND ws.code = 'prose' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'u-prirody-net-plohoy-pogody');
INSERT INTO works (author_user_id, section_id, title, slug, summary, body, excerpt, project_format, status, published_at, source_url) SELECT u.id, ws.id, 'Улыбка', 'ulybka-song', 'Проектный блок макета и одновременно трек радио.', 'Проектная карточка, синхронизированная с радио-макетом.', 'Проектная карточка, синхронизированная с радио-макетом.', 'song'::project_format, 'published', '2026-05-15T10:25:00+03:00', 'mockup://works' FROM users u CROSS JOIN work_sections ws WHERE u.login = 'ZVJOZDDOCHKA' AND ws.code = 'project' AND NOT EXISTS (SELECT 1 FROM works existing WHERE existing.slug = 'ulybka-song');

-- forum tags and topics from the mockup
INSERT INTO forum_tags (slug, name) VALUES ('тм', 'ТМ') ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO forum_tags (slug, name) VALUES ('критика', 'Критика') ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO forum_tags (slug, name) VALUES ('поэзия', 'Поэзия') ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO forum_tags (slug, name) VALUES ('лирика', 'Лирика') ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO forum_tags (slug, name) VALUES ('авторская', 'Авторская') ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO forum_tags (slug, name) VALUES ('проза', 'Проза') ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO forum_tags (slug, name) VALUES ('обсуждение', 'Обсуждение') ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO forum_topics (section_id, author_user_id, title, slug, body, replies_count, views_count, status, is_pinned, source_url, created_at, last_post_at) SELECT fs.id, u.id, 'Свои причины промолчать (ТМ)', 'svoi-prichiny-promolchat-tm', 'Тема из форумного макета: обсуждение причин молчания и пауз в тексте.', 14, 320, 'open', FALSE, 'mockup://forum', '2026-05-06T12:00:00+03:00', '2026-05-06T12:00:00+03:00' FROM forum_sections fs JOIN users u ON u.login = 'lone_traveler' WHERE fs.slug = 'tm' AND NOT EXISTS (SELECT 1 FROM forum_topics existing WHERE existing.slug = 'svoi-prichiny-promolchat-tm');
INSERT INTO forum_topic_tags (topic_id, tag_id) SELECT ft.id, tg.id FROM forum_topics ft CROSS JOIN forum_tags tg WHERE ft.slug = 'svoi-prichiny-promolchat-tm' AND tg.slug = 'тм' ON CONFLICT DO NOTHING;
INSERT INTO forum_topic_tags (topic_id, tag_id) SELECT ft.id, tg.id FROM forum_topics ft CROSS JOIN forum_tags tg WHERE ft.slug = 'svoi-prichiny-promolchat-tm' AND tg.slug = 'критика' ON CONFLICT DO NOTHING;
INSERT INTO forum_topics (section_id, author_user_id, title, slug, body, replies_count, views_count, status, is_pinned, source_url, created_at, last_post_at) SELECT fs.id, u.id, 'Мальчик — (Т.М.)', 'malchik-tm', 'Тема из форумного макета о поэтическом тексте «Мальчик».', 8, 180, 'open', FALSE, 'mockup://forum', '2026-05-09T12:00:00+03:00', '2026-05-09T12:00:00+03:00' FROM forum_sections fs JOIN users u ON u.login = 'david-tm' WHERE fs.slug = 'tm' AND NOT EXISTS (SELECT 1 FROM forum_topics existing WHERE existing.slug = 'malchik-tm');
INSERT INTO forum_topic_tags (topic_id, tag_id) SELECT ft.id, tg.id FROM forum_topics ft CROSS JOIN forum_tags tg WHERE ft.slug = 'malchik-tm' AND tg.slug = 'тм' ON CONFLICT DO NOTHING;
INSERT INTO forum_topic_tags (topic_id, tag_id) SELECT ft.id, tg.id FROM forum_topics ft CROSS JOIN forum_tags tg WHERE ft.slug = 'malchik-tm' AND tg.slug = 'поэзия' ON CONFLICT DO NOTHING;
INSERT INTO forum_topics (section_id, author_user_id, title, slug, body, replies_count, views_count, status, is_pinned, source_url, created_at, last_post_at) SELECT fs.id, u.id, 'В роще (ТМ)', 'v-roshche-tm', 'Тема из форумного макета с разбором текста «В роще».', 12, 210, 'open', FALSE, 'mockup://forum', '2026-05-08T12:00:00+03:00', '2026-05-08T12:00:00+03:00' FROM forum_sections fs JOIN users u ON u.login = 'curator-tm' WHERE fs.slug = 'tm' AND NOT EXISTS (SELECT 1 FROM forum_topics existing WHERE existing.slug = 'v-roshche-tm');
INSERT INTO forum_topic_tags (topic_id, tag_id) SELECT ft.id, tg.id FROM forum_topics ft CROSS JOIN forum_tags tg WHERE ft.slug = 'v-roshche-tm' AND tg.slug = 'тм' ON CONFLICT DO NOTHING;
INSERT INTO forum_topic_tags (topic_id, tag_id) SELECT ft.id, tg.id FROM forum_topics ft CROSS JOIN forum_tags tg WHERE ft.slug = 'v-roshche-tm' AND tg.slug = 'лирика' ON CONFLICT DO NOTHING;
INSERT INTO forum_topics (section_id, author_user_id, title, slug, body, replies_count, views_count, status, is_pinned, source_url, created_at, last_post_at) SELECT fs.id, u.id, 'Сочится жизнь (ТМ)', 'sochitsya-zhizn-tm', 'Тема из форумного макета о тексте «Сочится жизнь».', 6, 95, 'open', FALSE, 'mockup://forum', '2026-04-13T12:00:00+03:00', '2026-04-13T12:00:00+03:00' FROM forum_sections fs JOIN users u ON u.login = 'lf' WHERE fs.slug = 'tm' AND NOT EXISTS (SELECT 1 FROM forum_topics existing WHERE existing.slug = 'sochitsya-zhizn-tm');
INSERT INTO forum_topic_tags (topic_id, tag_id) SELECT ft.id, tg.id FROM forum_topics ft CROSS JOIN forum_tags tg WHERE ft.slug = 'sochitsya-zhizn-tm' AND tg.slug = 'тм' ON CONFLICT DO NOTHING;
INSERT INTO forum_topic_tags (topic_id, tag_id) SELECT ft.id, tg.id FROM forum_topics ft CROSS JOIN forum_tags tg WHERE ft.slug = 'sochitsya-zhizn-tm' AND tg.slug = 'авторская' ON CONFLICT DO NOTHING;
INSERT INTO forum_topics (section_id, author_user_id, title, slug, body, replies_count, views_count, status, is_pinned, source_url, created_at, last_post_at) SELECT fs.id, u.id, 'Последний день Трудоголикова', 'posledniy-den-trudogolikova', 'Обсуждение прозаического текста из форумного макета.', 11, 150, 'open', FALSE, 'mockup://forum', '2026-04-15T12:00:00+03:00', '2026-04-15T12:00:00+03:00' FROM forum_sections fs JOIN users u ON u.login = 'astsergey' WHERE fs.slug = 'general' AND NOT EXISTS (SELECT 1 FROM forum_topics existing WHERE existing.slug = 'posledniy-den-trudogolikova');
INSERT INTO forum_topic_tags (topic_id, tag_id) SELECT ft.id, tg.id FROM forum_topics ft CROSS JOIN forum_tags tg WHERE ft.slug = 'posledniy-den-trudogolikova' AND tg.slug = 'проза' ON CONFLICT DO NOTHING;
INSERT INTO forum_topic_tags (topic_id, tag_id) SELECT ft.id, tg.id FROM forum_topics ft CROSS JOIN forum_tags tg WHERE ft.slug = 'posledniy-den-trudogolikova' AND tg.slug = 'обсуждение' ON CONFLICT DO NOTHING;
INSERT INTO forum_topics (section_id, author_user_id, title, slug, body, replies_count, views_count, status, is_pinned, source_url, created_at, last_post_at) SELECT fs.id, u.id, 'Три куста (ТМ)', 'tri-kusta-tm', 'Тема из форумного макета о тексте «Три куста».', 4, 70, 'open', FALSE, 'mockup://forum', '2026-04-06T12:00:00+03:00', '2026-04-06T12:00:00+03:00' FROM forum_sections fs JOIN users u ON u.login = 'lf' WHERE fs.slug = 'tm' AND NOT EXISTS (SELECT 1 FROM forum_topics existing WHERE existing.slug = 'tri-kusta-tm');
INSERT INTO forum_topic_tags (topic_id, tag_id) SELECT ft.id, tg.id FROM forum_topics ft CROSS JOIN forum_tags tg WHERE ft.slug = 'tri-kusta-tm' AND tg.slug = 'тм' ON CONFLICT DO NOTHING;
INSERT INTO forum_topic_tags (topic_id, tag_id) SELECT ft.id, tg.id FROM forum_topics ft CROSS JOIN forum_tags tg WHERE ft.slug = 'tri-kusta-tm' AND tg.slug = 'критика' ON CONFLICT DO NOTHING;

-- forum posts mirroring the discussion mood from the mockup
INSERT INTO forum_posts (topic_id, author_user_id, parent_post_id, body, status, created_at) SELECT ft.id, u.id, NULL, 'В начале хорошо работает пауза, но концовку можно сделать ещё жёстче.', 'visible', '2026-05-06T13:00:00+03:00' FROM forum_topics ft JOIN users u ON u.login = 'curator-tm' WHERE ft.slug = 'svoi-prichiny-promolchat-tm' AND NOT EXISTS (SELECT 1 FROM forum_posts fp WHERE fp.topic_id = ft.id AND fp.author_user_id = u.id AND fp.body = 'В начале хорошо работает пауза, но концовку можно сделать ещё жёстче.');
INSERT INTO forum_posts (topic_id, author_user_id, parent_post_id, body, status, created_at) SELECT ft.id, u.id, NULL, 'Мне нравится образность, особенно переход от внутреннего молчания к внешнему жесту.', 'visible', '2026-05-06T14:30:00+03:00' FROM forum_topics ft JOIN users u ON u.login = 'lf' WHERE ft.slug = 'svoi-prichiny-promolchat-tm' AND NOT EXISTS (SELECT 1 FROM forum_posts fp WHERE fp.topic_id = ft.id AND fp.author_user_id = u.id AND fp.body = 'Мне нравится образность, особенно переход от внутреннего молчания к внешнему жесту.');
INSERT INTO forum_posts (topic_id, author_user_id, parent_post_id, body, status, created_at) SELECT ft.id, u.id, NULL, 'Ритм местами сбивается, но сама интонация держится очень уверенно.', 'visible', '2026-05-09T13:15:00+03:00' FROM forum_topics ft JOIN users u ON u.login = 'lone_traveler' WHERE ft.slug = 'malchik-tm' AND NOT EXISTS (SELECT 1 FROM forum_posts fp WHERE fp.topic_id = ft.id AND fp.author_user_id = u.id AND fp.body = 'Ритм местами сбивается, но сама интонация держится очень уверенно.');
INSERT INTO forum_posts (topic_id, author_user_id, parent_post_id, body, status, created_at) SELECT ft.id, u.id, NULL, 'Сильный образ мальчика, попробуй чуть сократить финальные строки.', 'visible', '2026-05-09T16:00:00+03:00' FROM forum_topics ft JOIN users u ON u.login = 'curator-tm' WHERE ft.slug = 'malchik-tm' AND NOT EXISTS (SELECT 1 FROM forum_posts fp WHERE fp.topic_id = ft.id AND fp.author_user_id = u.id AND fp.body = 'Сильный образ мальчика, попробуй чуть сократить финальные строки.');
INSERT INTO forum_posts (topic_id, author_user_id, parent_post_id, body, status, created_at) SELECT ft.id, u.id, NULL, 'Тут красиво собран пейзаж, особенно работает звукопись.', 'visible', '2026-05-08T13:40:00+03:00' FROM forum_topics ft JOIN users u ON u.login = 'lf' WHERE ft.slug = 'v-roshche-tm' AND NOT EXISTS (SELECT 1 FROM forum_posts fp WHERE fp.topic_id = ft.id AND fp.author_user_id = u.id AND fp.body = 'Тут красиво собран пейзаж, особенно работает звукопись.');
INSERT INTO forum_posts (topic_id, author_user_id, parent_post_id, body, status, created_at) SELECT ft.id, u.id, NULL, 'Я бы усилил вторую строфу и сделал контраст с первой заметнее.', 'visible', '2026-05-08T17:10:00+03:00' FROM forum_topics ft JOIN users u ON u.login = 'david-tm' WHERE ft.slug = 'v-roshche-tm' AND NOT EXISTS (SELECT 1 FROM forum_posts fp WHERE fp.topic_id = ft.id AND fp.author_user_id = u.id AND fp.body = 'Я бы усилил вторую строфу и сделал контраст с первой заметнее.');
INSERT INTO forum_posts (topic_id, author_user_id, parent_post_id, body, status, created_at) SELECT ft.id, u.id, NULL, 'Очень атмосферно, но можно добавить больше конкретики в середине текста.', 'visible', '2026-04-13T13:20:00+03:00' FROM forum_topics ft JOIN users u ON u.login = 'astsergey' WHERE ft.slug = 'sochitsya-zhizn-tm' AND NOT EXISTS (SELECT 1 FROM forum_posts fp WHERE fp.topic_id = ft.id AND fp.author_user_id = u.id AND fp.body = 'Очень атмосферно, но можно добавить больше конкретики в середине текста.');
INSERT INTO forum_posts (topic_id, author_user_id, parent_post_id, body, status, created_at) SELECT ft.id, u.id, NULL, 'Финал получился сильным, я бы только подчистил пару эпитетов.', 'visible', '2026-04-13T16:05:00+03:00' FROM forum_topics ft JOIN users u ON u.login = 'curator-tm' WHERE ft.slug = 'sochitsya-zhizn-tm' AND NOT EXISTS (SELECT 1 FROM forum_posts fp WHERE fp.topic_id = ft.id AND fp.author_user_id = u.id AND fp.body = 'Финал получился сильным, я бы только подчистил пару эпитетов.');
INSERT INTO forum_posts (topic_id, author_user_id, parent_post_id, body, status, created_at) SELECT ft.id, u.id, NULL, 'Проза держит темп, особенно понравился нерв последней сцены.', 'visible', '2026-04-15T13:35:00+03:00' FROM forum_topics ft JOIN users u ON u.login = 'lf' WHERE ft.slug = 'posledniy-den-trudogolikova' AND NOT EXISTS (SELECT 1 FROM forum_posts fp WHERE fp.topic_id = ft.id AND fp.author_user_id = u.id AND fp.body = 'Проза держит темп, особенно понравился нерв последней сцены.');
INSERT INTO forum_posts (topic_id, author_user_id, parent_post_id, body, status, created_at) SELECT ft.id, u.id, NULL, 'Герой получился живым — хочется только чуть прибрать экспозицию.', 'visible', '2026-04-15T18:00:00+03:00' FROM forum_topics ft JOIN users u ON u.login = 'lone_traveler' WHERE ft.slug = 'posledniy-den-trudogolikova' AND NOT EXISTS (SELECT 1 FROM forum_posts fp WHERE fp.topic_id = ft.id AND fp.author_user_id = u.id AND fp.body = 'Герой получился живым — хочется только чуть прибрать экспозицию.');
INSERT INTO forum_posts (topic_id, author_user_id, parent_post_id, body, status, created_at) SELECT ft.id, u.id, NULL, 'Короткая форма здесь работает, три образа действительно держат текст.', 'visible', '2026-04-06T13:00:00+03:00' FROM forum_topics ft JOIN users u ON u.login = 'curator-tm' WHERE ft.slug = 'tri-kusta-tm' AND NOT EXISTS (SELECT 1 FROM forum_posts fp WHERE fp.topic_id = ft.id AND fp.author_user_id = u.id AND fp.body = 'Короткая форма здесь работает, три образа действительно держат текст.');
INSERT INTO forum_posts (topic_id, author_user_id, parent_post_id, body, status, created_at) SELECT ft.id, u.id, NULL, 'Финальная строка удачная, я бы её оставил без изменений.', 'visible', '2026-04-06T15:45:00+03:00' FROM forum_topics ft JOIN users u ON u.login = 'david-tm' WHERE ft.slug = 'tri-kusta-tm' AND NOT EXISTS (SELECT 1 FROM forum_posts fp WHERE fp.topic_id = ft.id AND fp.author_user_id = u.id AND fp.body = 'Финальная строка удачная, я бы её оставил без изменений.');

-- contests from the mockup
INSERT INTO contests (title, slug, description, contest_scope, status, starts_at, submission_ends_at, voting_ends_at, results_published_at, cover_image_url, source_url) VALUES ('Здесь начинается Россия', 'zdes-nachinaetsya-rossiya', 'Конкурс сайта из макета: «Здесь начинается Россия».', 'site'::contest_scope, 'voting'::contest_status, '2026-05-25T00:00:00+03:00', '2026-06-05T23:59:00+03:00', '2026-06-12T23:59:00+03:00', '2026-06-15T12:00:00+03:00', 'https://www.chitalnya.ru/upload/960/c3767bc0e640c7ce33ee51d9413d05f2.jpg', 'https://www.chitalnya.ru/users/contest/') ON CONFLICT (slug) DO UPDATE SET description = EXCLUDED.description, contest_scope = EXCLUDED.contest_scope, status = EXCLUDED.status, starts_at = EXCLUDED.starts_at, submission_ends_at = EXCLUDED.submission_ends_at, voting_ends_at = EXCLUDED.voting_ends_at, results_published_at = EXCLUDED.results_published_at, cover_image_url = EXCLUDED.cover_image_url, source_url = EXCLUDED.source_url;
INSERT INTO contests (title, slug, description, contest_scope, status, starts_at, submission_ends_at, voting_ends_at, results_published_at, cover_image_url, source_url) VALUES ('Конкурс декламаций «История любви»', 'konkurs-deklamacij-istoriya-lyubvi', 'Конкурс декламаций из макета, этап приёма работ.', 'site'::contest_scope, 'accepting_entries'::contest_status, '2026-05-13T00:00:00+03:00', '2026-06-28T23:59:00+03:00', '2026-07-05T23:59:00+03:00', '2026-07-10T12:00:00+03:00', 'https://www.chitalnya.ru/cache_image/3a/3a0bb9d12be6a2f3c10d37dfd1a46969.jpg', 'https://www.chitalnya.ru/users/cup.izba') ON CONFLICT (slug) DO UPDATE SET description = EXCLUDED.description, contest_scope = EXCLUDED.contest_scope, status = EXCLUDED.status, starts_at = EXCLUDED.starts_at, submission_ends_at = EXCLUDED.submission_ends_at, voting_ends_at = EXCLUDED.voting_ends_at, results_published_at = EXCLUDED.results_published_at, cover_image_url = EXCLUDED.cover_image_url, source_url = EXCLUDED.source_url;
INSERT INTO contests (title, slug, description, contest_scope, status, starts_at, submission_ends_at, voting_ends_at, results_published_at, cover_image_url, source_url) VALUES ('Друг человека (Поэзия)', 'drug-cheloveka-poeziya', '1 место — «О нас так вряд ли...» (Анжела Баер); 2 место — «Недолог век собаки на войне» (Сергей Анашкин); 3 место — «Старым собакам» (Lusia Rozanova).', 'site'::contest_scope, 'finished'::contest_status, '2026-03-01T00:00:00+03:00', '2026-03-20T23:59:00+03:00', '2026-03-28T23:59:00+03:00', '2026-03-30T12:00:00+03:00', NULL, 'https://www.chitalnya.ru/forum.php?t=13') ON CONFLICT (slug) DO UPDATE SET description = EXCLUDED.description, contest_scope = EXCLUDED.contest_scope, status = EXCLUDED.status, starts_at = EXCLUDED.starts_at, submission_ends_at = EXCLUDED.submission_ends_at, voting_ends_at = EXCLUDED.voting_ends_at, results_published_at = EXCLUDED.results_published_at, cover_image_url = EXCLUDED.cover_image_url, source_url = EXCLUDED.source_url;
INSERT INTO contests (title, slug, description, contest_scope, status, starts_at, submission_ends_at, voting_ends_at, results_published_at, cover_image_url, source_url) VALUES ('Друг человека (Проза)', 'drug-cheloveka-proza', '1 место — «Собака - подрывник Джульбарс» (Вера Павлова); 2 место — «Герд» (Сергей Богаткин); 3 место — «Как сочинялась опера» (Ольга Зимина).', 'site'::contest_scope, 'finished'::contest_status, '2026-03-01T00:00:00+03:00', '2026-03-20T23:59:00+03:00', '2026-03-28T23:59:00+03:00', '2026-03-30T12:30:00+03:00', NULL, 'https://www.chitalnya.ru/forum.php?t=13') ON CONFLICT (slug) DO UPDATE SET description = EXCLUDED.description, contest_scope = EXCLUDED.contest_scope, status = EXCLUDED.status, starts_at = EXCLUDED.starts_at, submission_ends_at = EXCLUDED.submission_ends_at, voting_ends_at = EXCLUDED.voting_ends_at, results_published_at = EXCLUDED.results_published_at, cover_image_url = EXCLUDED.cover_image_url, source_url = EXCLUDED.source_url;
INSERT INTO contests (title, slug, description, contest_scope, status, starts_at, submission_ends_at, voting_ends_at, results_published_at, cover_image_url, source_url) VALUES ('История. События (Поэзия)', 'istoriya-sobytiya-poeziya', '1 место — «накануне...» (Дана Верис); 2 место — «Горюн-трава» (Явецкий Павел); 3 место — «Ангелы с чёрными лицами» (Тианна Ридак).', 'site'::contest_scope, 'finished'::contest_status, '2026-02-01T00:00:00+03:00', '2026-02-18T23:59:00+03:00', '2026-02-26T23:59:00+03:00', '2026-02-28T12:00:00+03:00', NULL, 'https://www.chitalnya.ru/forum.php?t=13') ON CONFLICT (slug) DO UPDATE SET description = EXCLUDED.description, contest_scope = EXCLUDED.contest_scope, status = EXCLUDED.status, starts_at = EXCLUDED.starts_at, submission_ends_at = EXCLUDED.submission_ends_at, voting_ends_at = EXCLUDED.voting_ends_at, results_published_at = EXCLUDED.results_published_at, cover_image_url = EXCLUDED.cover_image_url, source_url = EXCLUDED.source_url;
INSERT INTO contests (title, slug, description, contest_scope, status, starts_at, submission_ends_at, voting_ends_at, results_published_at, cover_image_url, source_url) VALUES ('История. События (Проза)', 'istoriya-sobytiya-proza', '1 место — «Трагедия 1969 года» (Сергей НикулинЪ); 2 место — «Точка невозврата» (Даре Мачавариани); 3 место — «Не трогай мою игрушку!» (Сергей Кабских).', 'site'::contest_scope, 'finished'::contest_status, '2026-02-01T00:00:00+03:00', '2026-02-18T23:59:00+03:00', '2026-02-26T23:59:00+03:00', '2026-02-28T12:30:00+03:00', NULL, 'https://www.chitalnya.ru/forum.php?t=13') ON CONFLICT (slug) DO UPDATE SET description = EXCLUDED.description, contest_scope = EXCLUDED.contest_scope, status = EXCLUDED.status, starts_at = EXCLUDED.starts_at, submission_ends_at = EXCLUDED.submission_ends_at, voting_ends_at = EXCLUDED.voting_ends_at, results_published_at = EXCLUDED.results_published_at, cover_image_url = EXCLUDED.cover_image_url, source_url = EXCLUDED.source_url;

-- radio from the mockup
INSERT INTO radio_streams (name, stream_url, page_url, chat_url, is_active) VALUES ('Литопотам Радио', 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', 'https://www.chitalnya.ru/radio/', 'https://www.chitalnya.ru/radio/', TRUE) ON CONFLICT DO NOTHING;
INSERT INTO radio_tracks (title, author_name, duration_seconds, audio_url, source_url) SELECT 'Улыбка', 'Шаинский / Пляцковский', 154, 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', 'https://www.chitalnya.ru/radio/' WHERE NOT EXISTS (SELECT 1 FROM radio_tracks existing WHERE existing.title = 'Улыбка' AND coalesce(existing.author_name, '') = coalesce('Шаинский / Пляцковский', ''));
INSERT INTO radio_tracks (title, author_name, duration_seconds, audio_url, source_url) SELECT 'Ночная лампа', 'Николай Иванов', 192, NULL, 'https://www.chitalnya.ru/radio/' WHERE NOT EXISTS (SELECT 1 FROM radio_tracks existing WHERE existing.title = 'Ночная лампа' AND coalesce(existing.author_name, '') = coalesce('Николай Иванов', ''));
INSERT INTO radio_tracks (title, author_name, duration_seconds, audio_url, source_url) SELECT 'Вчера вечером', 'Марина Любимова', 225, NULL, 'https://www.chitalnya.ru/radio/' WHERE NOT EXISTS (SELECT 1 FROM radio_tracks existing WHERE existing.title = 'Вчера вечером' AND coalesce(existing.author_name, '') = coalesce('Марина Любимова', ''));

-- comments and ratings derived from the mockup discussion/review blocks
INSERT INTO work_comments (work_id, user_id, parent_comment_id, body, status, created_at) SELECT w.id, u.id, NULL, 'Тонко выстроенная мистическая интонация — текст хочется перечитать ещё раз.', 'visible', '2026-05-15T11:15:00+03:00' FROM works w JOIN users u ON u.login = 'elizabet-velyamin-skaya' WHERE w.slug = 'skazanie-o-shamanke-nini' AND NOT EXISTS (SELECT 1 FROM work_comments existing WHERE existing.work_id = w.id AND existing.user_id = u.id AND existing.body = 'Тонко выстроенная мистическая интонация — текст хочется перечитать ещё раз.');
INSERT INTO work_comments (work_id, user_id, parent_comment_id, body, status, created_at) SELECT w.id, u.id, NULL, 'Хорошо работает философская нота и пауза между строками.', 'visible', '2026-05-15T11:25:00+03:00' FROM works w JOIN users u ON u.login = 'tais-nikolskaya' WHERE w.slug = 'poeziya-loranna' AND NOT EXISTS (SELECT 1 FROM work_comments existing WHERE existing.work_id = w.id AND existing.user_id = u.id AND existing.body = 'Хорошо работает философская нота и пауза между строками.');
INSERT INTO work_comments (work_id, user_id, parent_comment_id, body, status, created_at) SELECT w.id, u.id, NULL, 'Очень музыкальный ритм, особенно удачна последняя строфа.', 'visible', '2026-05-15T11:35:00+03:00' FROM works w JOIN users u ON u.login = 'elizabet-velyamin-skaya' WHERE w.slug = 'solvejg' AND NOT EXISTS (SELECT 1 FROM work_comments existing WHERE existing.work_id = w.id AND existing.user_id = u.id AND existing.body = 'Очень музыкальный ритм, особенно удачна последняя строфа.');
INSERT INTO work_ratings (work_id, user_id, rating) SELECT w.id, u.id, 5 FROM works w JOIN users u ON u.login = 'Stan242' WHERE w.slug = 'skazanie-o-shamanke-nini' ON CONFLICT (work_id, user_id) DO UPDATE SET rating = EXCLUDED.rating;
INSERT INTO work_ratings (work_id, user_id, rating) SELECT w.id, u.id, 4 FROM works w JOIN users u ON u.login = 'Dave_Gahan' WHERE w.slug = 'skazanie-o-shamanke-nini' ON CONFLICT (work_id, user_id) DO UPDATE SET rating = EXCLUDED.rating;
INSERT INTO work_ratings (work_id, user_id, rating) SELECT w.id, u.id, 5 FROM works w JOIN users u ON u.login = 'the_king_of_words' WHERE w.slug = 'poeziya-loranna' ON CONFLICT (work_id, user_id) DO UPDATE SET rating = EXCLUDED.rating;
INSERT INTO work_ratings (work_id, user_id, rating) SELECT w.id, u.id, 4 FROM works w JOIN users u ON u.login = 'ergin' WHERE w.slug = 'solvejg' ON CONFLICT (work_id, user_id) DO UPDATE SET rating = EXCLUDED.rating;
INSERT INTO work_ratings (work_id, user_id, rating) SELECT w.id, u.id, 5 FROM works w JOIN users u ON u.login = 'antonborovikov' WHERE w.slug = 'ulybka-song' ON CONFLICT (work_id, user_id) DO UPDATE SET rating = EXCLUDED.rating;
INSERT INTO work_ratings (work_id, user_id, rating) SELECT w.id, u.id, 4 FROM works w JOIN users u ON u.login = 'Ardak1977' WHERE w.slug = 'chernye-monety' ON CONFLICT (work_id, user_id) DO UPDATE SET rating = EXCLUDED.rating;

-- keep derived counters aligned with seeded rows
UPDATE author_profiles ap SET works_count_cached = stats.cnt FROM ( SELECT author_user_id, count(*)::int AS cnt FROM works GROUP BY author_user_id) stats WHERE ap.user_id = stats.author_user_id;
UPDATE works w SET comments_count = stats.cnt FROM ( SELECT work_id, count(*)::int AS cnt FROM work_comments GROUP BY work_id) stats WHERE w.id = stats.work_id;
UPDATE works SET comments_count = 0 WHERE comments_count IS NULL;
UPDATE works w SET ratings_count = stats.cnt, average_rating = stats.avg_rating FROM ( SELECT work_id, count(*)::int AS cnt, avg(rating)::numeric(4,2) AS avg_rating FROM work_ratings GROUP BY work_id) stats WHERE w.id = stats.work_id;
UPDATE works SET ratings_count = 0 WHERE ratings_count IS NULL;
UPDATE works SET average_rating = 0 WHERE average_rating IS NULL;
UPDATE forum_topics ft SET replies_count = stats.cnt, last_post_at = stats.last_post_at FROM ( SELECT topic_id, count(*)::int AS cnt, max(created_at) AS last_post_at FROM forum_posts GROUP BY topic_id) stats WHERE ft.id = stats.topic_id;

COMMIT;
